### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by danielonges** [AY2021S2-CS2103-T14-4/tp#1]
Our team's brainstorming of user stories

**Comment by austenjs** [comment]
1. As a CS student who does tasks near deadlines, I want to know which task is coming the soonest, so that I can finish it first.
2. As a CS student who has recurring tasks every period of time (e.g. weekly, monthly, etc), I want to add the task and set a recurring time, so that I don't need to add the same task multiple times.
3. As a CS student, I want to have notes for each task, so that I remember important information about the task
4. As a CS student, I want to sort deadlines from each module, so I can estimate how much workload needed for each module
5. As a CS student, I want to put multiple tasks instantly, so that I don't need to submit multiple times
6. As a CS student, I want my reminders to show the module code and name
7. As a CS student, I want to move the reminders easily, so that if the deadline change I can change the reminder easily
8. As a CS student, I want to know how many deadlines I have and how many deadlines I have done, so I can know whether I am lacking behind or not
9. As a CS student, I want to have the email of the prof or ta of the module, so that I can contact them if I have an issue with a deadline
10. As a CS student who just finished a holiday, I want to reset my calendar, so that I can start a new semester with new deadlines

**Comment by geraldfan** [comment]
1. As a busy CS student, I want to know which deadlines are coming up, so I can focus on them first.
2. As a CS student who has weekly quizzes, I can be alerted when the deadline of the quiz is coming up, so that I don't miss any quiz.
3. As a CS student, I can check my module deadlines and information at the same location, so that I don't have to navigate between multiple tabs.
4.As a CS student, I can set notes for the tasks, to record information about the task.
5.As a CS student, I can break a task down into several smaller tasks to better organize my tasks
6.As a CS student, I can view my schedule in calendar format to better plan my time.
7.As a first-time user, I can view a help message explaining the features so that I can orientate myself with the app
8.As a CS student, I can delete tasks that I no longer need to track.

**Comment by mrweikiat** [comment]
1. As an SoC student I can filter out non-soc and soc assignments and tasks to improve productivity
2. As an SoC student i can manage CS coded deadlines by itself since they are not mixed with other faculties mods
3. As an SoC student I can set reminders for CS coded modules to remind myself of deadlines
4. As an Soc student i often mix up SoC mods deadlines with other modules, reducing my productivity
5. As an SoC student, I want to know my CS assignments and deadlines well so i will not confuse with other mods
6. As an SoC student, I can focus more on my core CS modules by filtering out using the SW
7. As an SoC Student, I can delete, edit and add CS assignments that are often my core modules. So that I can concentrate better
8. As an SoC student, I want to finish the CS coded assignments first before other non-CS mods, this SW can consolidate all CS assignments

**Comment by danielonges** [comment]
1. As a CS student, I want to be able to record down all my upcoming deadlines and assignments so that I have a clearer view on how to manage my time effectively.
2. As a CS student, I would like to sort my deadlines according to the most urgent ones first, so that I can prioritise my work better.
3. Being a CS students with many other commitments, I would appreciate reminders when I have a CS related deadline approaching, as I might forget some of them due to my busy schedule.
4. As a CS student that probably has multiple ongoing coding projects, I can tag each project with the language(s) that they are written in, so I know which languages I need to be proficient in
5. As a CS student, I can tag each assignment with a priority level so that I know where to focus my efforts on.
6. As a CS student that does work daily, I would like to be able to assign my tasks to a daily to-do list so that I can plan out my day and the work that I need to accomplish for that day.
7. As a CS student, I would like to be able to make quick notes on the assignments that I have noted down. This could help me get out a quick idea, or leave remarks on certain tasks that might be relevant.
8. As a CS student, I can mark assignments that I have finished as completed so that it lets me feel a sense of accomplishment.
